visual_smog_map/map/urls.py
"""
URL routing mapping for the map app.

Jakub Svoboda, 2023
"""

from typing import List

from django.urls import URLPattern, path

from . import views

app_name = "map"
urlpatterns: List[URLPattern] = [
    path("", views.index, name="index"),
    # ex: /billboards/
    path("billboards/", views.billboards, name="billboards"),
    # ex: /billboards/5/
    path("billboards/<int:billboard_id>/", views.detail, name="detail"),
    # ex: /billboards/create
    path("billboards/create/", views.create, name="create"),
    # ex: /billboards/save
    path("billboards/save/", views.save, name="save"),
]

visual_smog_map/visual_smog_map/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("", include("map.urls")),
    path('admin/', admin.site.urls),
]

visual_smog_map/map/models.py
"""
Define all models here.

Jakub Svoboda, 2023
"""

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


# Create your models here.
class Smog(models.Model):
    """
    Model represents a single piece of visual smog (usually a single billboard
    """

    name = models.CharField(max_length=300)
    note = models.CharField(max_length=3000)
    parcel = models.CharField(max_length=300)
    lv = models.CharField(max_length=300)
    legality_status = models.CharField(max_length=300)
    latitude = models.FloatField(
        validators=[MinValueValidator(-180.0), MaxValueValidator(180.0)]
    )  # Latitude range: -180 to 180 degrees
    longitude = models.FloatField(
        validators=[MinValueValidator(-180.0), MaxValueValidator(180.0)]
    )  # Longitude range: -180 to 180 degrees
    cadaster = models.CharField(max_length=500)
    pub_date = models.DateTimeField("date published")
    approved = models.BooleanField(default=False)

    def __str__(self):
        return str(self.name)

visual_smog_map/map/forms.py
"""
Contains input forms specification.

Jakub Svoboda, 2023
"""

from django import forms

from .models import Smog


class SmogForm(forms.ModelForm):
    """
    Basic input form for adding new billboards to the system.
    """

    class Meta:
        model = Smog
        fields = [
            "name",
            "note",
            "parcel",
            "lv",
            "legality_status",
            "latitude",
            "longitude",
            "cadaster",
        ]

    LEGALITY_STATUS_CHOICES = [
        ("Legal", "Legal"),
        ("Illegal", "Illegal"),
        ("Unknown", "Unknown"),
    ]

    legality_status = forms.ChoiceField(choices=LEGALITY_STATUS_CHOICES)
    latitude = forms.DecimalField(max_digits=9, decimal_places=6)
    longitude = forms.DecimalField(max_digits=9, decimal_places=6)

visual_smog_map/map/views.py
"""
Views of the map app.

Jakub Svoboda, 2023
"""

import os
from datetime import datetime

from django.http import HttpRequest, HttpResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404, redirect, render
from django.template import loader
from django.urls import reverse

from .forms import SmogForm
from .models import Smog


# Create your views here.
def index(request: HttpRequest) -> HttpResponse:
    """
    Homepage view.
    """
    smog_list = Smog.objects.all()
    context = {"smog_list": smog_list, "GOOGLE_APIKEY": str(os.getenv("GOOGLE_APIKEY"))}
    template = loader.get_template("map/index.html")
    return HttpResponse(template.render(context, request))


def billboards(request: HttpRequest) -> HttpResponse:
    """
    View of billboard database.
    """
    legality_filter = request.GET.get("legality_filter", "All")
    if legality_filter == "All":
        smog_list = Smog.objects.all()
    else:
        smog_list = Smog.objects.filter(legality_status=legality_filter)
    context = {
        "smog_list": smog_list,
        "legality_filter": legality_filter,
        "GOOGLE_APIKEY": str(os.getenv("GOOGLE_APIKEY")),
    }
    template = loader.get_template("map/billboards.html")
    return HttpResponse(template.render(context, request))


def detail(request: HttpRequest, billboard_id: int) -> HttpResponse:
    """
    View of a single billboard with its details.
    """
    billboard = get_object_or_404(Smog, pk=billboard_id)
    return render(request, "map/detail.html", {"billboard": billboard})


def create(request: HttpRequest) -> HttpResponse:
    """
    View the form for adding new billboards.
    """
    if request.method == "POST":
        form = SmogForm(request.POST)
        if form.is_valid():
            smog_obj = form.save(commit=False)
            smog_obj.pub_date = (
                datetime.now()
            )  # Set the publication date to the current date and time
            smog_obj.save()
            return redirect("map:detail", billboard_id=smog_obj.id)
    else:
        form = SmogForm()

    return render(request, "map/create.html", {"form": form})


def save(request: HttpRequest) -> HttpResponse:
    """
    View for when a new billboard gets added.
    """
    if request.method == "POST":
        name = request.POST["name"]
        note = request.POST["note"]
        parcel = request.POST["parcel"]
        lv = request.POST["lv"]
        legality_status = request.POST["legality_status"]
        latitude = request.POST["latitude"]
        longitude = request.POST["longitude"]
        cadaster = request.POST["cadaster"]
        pub_date = request.POST["pub_date"]

        # Create the Smog object and save it to the database
        smog_obj = Smog(
            name=name,
            note=note,
            parcel=parcel,
            lv=lv,
            legality_status=legality_status,
            latitude=latitude,
            longitude=longitude,
            cadaster=cadaster,
            pub_date=pub_date,
        )
        smog_obj.save()

        return redirect(reverse("map:detail", args=[smog_obj.id]))

    return HttpResponseNotFound("POST is the only supported method.")

visual_smog_map/map/templates/map/billboards.html
{% extends 'map/template.html' %}
{% block title %}My View Title{% endblock %}
{% block content %}
    <div class="w3-container w3-padding-32" id="projects">
        <h2 class="w3-border-bottom w3-border-light-grey w3-padding-16">Billboard Database</h2>
    </div>

    <div class="flex-container">
        <div class="map-container w3-container w3-padding-32">
            {% include 'map/map_full.html' %}
        </div>
        <div class="list-container w3-padding-32">
            <button class="w3-button w3-blue" onclick="window.location.href='{% url 'map:create' %}'">Add billboard</button>

            {% include "map/billboards_filter.html" %}    

            {% if smog_list %}
                <table class="w3-table-all w3-margin-top">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Note</th>
                            <th>Legality Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for smog in smog_list %}
                            {% if smog.approved %}
                                <tr>
                                    <td><a href="{% url 'map:detail' smog.id %}">{{ smog.name }}</a></td>
                                    <td>{{ smog.note }}</td>
                                    <td>{{ smog.legality_status }}</td>
                                    {% comment %} <td><a href="{% url 'map:edit' smog.id %}">Edit</a> | <a href="{% url 'map:delete' smog.id %}">Delete</a></td> {% endcomment %}
                                </tr>
                            {% endif %}    
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No billboards are available.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

visual_smog_map/map/templates/map/billboards_filter.html
<div class="w3-padding-top-32">
    <form method="get">                
        <label for="search">Filter billboards:</label>
        <select name="legality_filter" id="legality_filter">
            <option value="All" {% if legality_filter == 'All' %}selected{% endif %} >All</option>
            <option value="Legal" {% if legality_filter == 'Legal' %}selected{% endif %}>Legal</option>
            <option value="Illegal" {% if legality_filter == 'Illegal' %}selected{% endif %}>Illegal</option>
            <option value="Unknown" {% if legality_filter == 'Unknown' %}selected{% endif %}>Unknown</option>
        </select>
        <button type="submit">Apply filter</button>
    </form>
</div>

visual_smog_map/map/templates/map/create.html
{% extends 'map/template.html' %}
{% block title %}My View Title{% endblock %}
{% block content %}
    <div class="w3-container w3-padding-32" id="projects">
        <h2 class="w3-border-bottom w3-border-light-grey w3-padding-16">Add a new billboard</h2>
    </div>
    <div class="w3-container">
        {% comment %} <a href="{% url 'map:billboards' %}">Back to all billboards</a> {% endcomment %}
        <form method="post">
            {% csrf_token %}
            <fieldset>
                {% comment %} <legend><h1>Add a new billboard</h1></legend> {% endcomment %}
                {{ form.as_p }}
            </fieldset>
            <input type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

visual_smog_map/map/templates/map/detail.html
{% extends 'map/template.html' %}
{% block title %}My View Title{% endblock %}
{% block content %}
    <div class="w3-container w3-padding-32" id="projects">
        <h2 class="w3-border-bottom w3-border-light-grey w3-padding-16">{{ billboard.name }}</h2>
    </div>
    <div class="w3-container">
        {% comment %} <a href="{% url 'map:billboards' %}">Back to all billboards</a> {% endcomment %}
        <p>Legality status: {{ billboard.legality_status }}</p>
        <p>Note: {{ billboard.note }}</p>
        <p>Latitude: {{ billboard.latitude }}</p>
        <p>Longitude: {{ billboard.longitude }}</p>
        <p>Parcel: {{ billboard.parcel }}</p>
        <p>LV: {{ billboard.lv }}</p>
        <p>Cadaster: {{ billboard.cadaster }}</p>
        <p>Date added: {{ billboard.pub_date }}</p>
        <p>Approved: {{ billboard.approved }}</p>
    </div>
{% endblock %}

visual_smog_map/map/templates/map/index.html
{% extends 'map/template.html' %}
{% block title %}My View Title{% endblock %}
{% block content %}
    <div class="w3-container w3-padding-32" id="projects">
        <h2 class="w3-border-bottom w3-border-light-grey w3-padding-16">Billboard Map</h2>
    </div>

    <div class="flex-container">
        <div class="description-container w3-container w3-padding-32">
            <p>Project description placeholder text. Project description placeholder text. Project description placeholder text. Project description placeholder text.</p>
        </div>
        <div class="map-container w3-container w3-padding-32">
            {% include 'map/map_full.html' %}
        </div>
    </div>
{% endblock %}

visual_smog_map/map/templates/map/map_full.html
<div id="map" style="width:100%;height:500px;"></div>
<script>
    var map;
    var infoWindow;

    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: 49.7587, lng: 15.4269},
            zoom: 7
        });
        
        infoWindow = new google.maps.InfoWindow(); 
        
        {% if smog_list %}
            {% for smog in smog_list %}
                var marker = new google.maps.Marker({
                    position: { lat: {{ smog.latitude }}, lng: {{ smog.longitude }} },
                    {% comment %} animation: google.maps.Animation.BOUNCE, {% endcomment %}
                    map: map,
                    icon: {
                        {% if smog.legality_status == 'Illegal' %}
                            url: "http://maps.google.com/mapfiles/ms/icons/red.png",
                        {% elif smog.legality_status == 'Legal' %}
                            url: "http://maps.google.com/mapfiles/ms/icons/green.png",
                        {% elif smog.legality_status == 'Unknown' %}
                            url: "http://maps.google.com/mapfiles/ms/icons/yellow.png",
                        {% endif %}
                    }
                });

                marker.addListener('click', function() {
                    var content = "<strong>Name: " + "{{ smog.name }}" + " </strong> </br>" 
                    + "<strong>Legality Status: " + "{{ smog.legality_status }}" + " </strong>" 
                    infoWindow.setContent(content);
                    infoWindow.open(map, marker);
                    infoWindow.setPosition(new google.maps.LatLng({{ smog.latitude }}, {{ smog.longitude }}));
                }); 

            {% endfor %}
        {% endif %}
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_APIKEY }}&callback=initMap" async defer></script>

visual_smog_map/map/templates/map/template.html
<!DOCTYPE html>
<html>
<head>
<title>Visual Smog Map</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}
<link rel="stylesheet" href="{% static 'map/w3.css' %}">
<link rel="icon" type="image/x-icon" href="{% static 'map/favicon.ico' %}">
</head>

<body>
<!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar w3-white w3-wide w3-padding w3-card">
    <a href="{% url 'map:index' %}" class="w3-bar-item w3-button"><b>Billboard</b> Map</a>
    <!-- Float links to the right. Hide them on small screens -->
    <div class="w3-right w3-hide-small">
      <a href="{% url 'map:index' %}" class="w3-bar-item w3-button">Home</a>
      <a href="{% url 'map:billboards' %}" class="w3-bar-item w3-button">Database</a>
      <a href="#login" class="w3-bar-item w3-button">Login</a>
    </div>
  </div>
</div>

<!-- Header -->
<header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
  {% comment %} <img class="w3-image" src="/w3images/architect.jpg" alt="Architecture" width="1500" height="800"> {% endcomment %}
  {% comment %} <div class="w3-display-middle w3-margin-top w3-center">
    <h1 class="w3-xxlarge w3-text-white"><span class="w3-padding w3-black w3-opacity-min"><b>Billboard tracker</b></span> <span class="w3-hide-small w3-text-light-grey">Architects</span></h1>
  </div> {% endcomment %}
</header>

<!-- Page content -->
<div class="w3-content w3-padding" style="max-width:1564px">

    <a href="{% url 'map:billboards' %}">Browse the database of billboards</a>
    <!-- Project Section -->
   
    <div class="w3-container w3-padding-32" id="content">
        {% block content %}{% endblock %}
    </div>

<!-- End page content -->
</div>


<!-- Footer -->
{% comment %} <footer class="w3-center w3-black w3-padding-16">
  <p>Create by Someone title="W3.CSS" target="_blank" class="w3-hover-text-green">w3.css</a></p>
</footer> {% endcomment %}

</body>
</html>